### ISSUE TITLE
Implement Const DateTimeRange

### ISSUE THREAD

**Issue by benastorga** [westy92/const-date-time#11]
Currently using 
`const DateTimeRange(start: ConstDateTime(2024), end: ConstDateTime(2024))`
still throws an error because of the DateTimeRange constructor not being constant.

Can you add ConstDateTimeRange(…) ?

Thanks!

**Comment by westy92** [comment]
Thank you for the feature request! I'll weigh the pros/cons of adding this vs. creating a new package that builds upon this.
My only hesitation is that `DateTimeRange` is part of the [Flutter](https://api.flutter.dev/flutter/material/DateTimeRange-class.html) library, but this package presently has no dependence on Flutter.

**Comment by westy92** [comment]
Published [here](https://pub.dev/packages/const_date_time_range)!
